
export const PROJECT_UPLOAD_REQUEST = "PROJECT_UPLOAD_REQUEST";
export const PROJECT_UPLOAD_FAILURE = "PROJECT_UPLOAD_FAILURE";
export const GET_PROJECT_UPLOADS    = "GET_PROJECT_UPLOADS";
export const GET_PARTICULAR_UPLOAD    = "GET_PARTICULAR_UPLOAD";
export const CREATE_PROJECT_UPLOADS = "CREATE_PROJECT_UPLOADS";
export const DELETE_PROJECT_UPLOADS = "DELETE_PROJECT_UPLOADS";
export const EDIT_PROJECT_UPLOADS = "EDIT_PROJECT_UPLOADS";